const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  startRecording: (options) => ipcRenderer.invoke('start-recording', options),
  stopRecording: () => ipcRenderer.invoke('stop-recording'),
  getStatus: () => ipcRenderer.invoke('get-status'),
  getRemoteInfo: () => ipcRenderer.invoke('get-remote-info'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  activateConnection: (payload) => ipcRenderer.invoke('activate-connection', payload),
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  transferDevices: () => ipcRenderer.invoke('transfer-devices'),
  transferList: (payload) => ipcRenderer.invoke('transfer-list', payload),
  transferChooseFiles: () => ipcRenderer.invoke('transfer-choose-files'),
  transferChooseSaveDir: () => ipcRenderer.invoke('transfer-choose-save-dir'),
  transferPush: (payload) => ipcRenderer.invoke('transfer-push', payload),
  transferPull: (payload) => ipcRenderer.invoke('transfer-pull', payload),
  transferPreview: (payload) => ipcRenderer.invoke('transfer-preview', payload),
  openPath: (target) => ipcRenderer.invoke('open-path', target),
  automationList: () => ipcRenderer.invoke('automation-list'),
  runAutomation: (sceneId) => ipcRenderer.invoke('automation-run', { sceneId }),
  stopAutomation: () => ipcRenderer.invoke('automation-stop'),

  onRecordingStarted: (callback) => ipcRenderer.on('recording-started', (event, data) => callback(data)),
  onRecordingStopped: (callback) => ipcRenderer.on('recording-stopped', () => callback()),
  onRecordingError: (callback) => ipcRenderer.on('recording-error', (event, msg) => callback(msg)),
  onStatusText: (callback) => ipcRenderer.on('status-text', (event, text) => callback(text)),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, data) => callback(data)),
  onAutomationProgress: (callback) => ipcRenderer.on('automation-progress', (event, data) => callback(data)),
});
